### PR TITLE
fix disableNonBlockingReceive

### PR DESCRIPTION
**Pull request by HeMe2**
- unset callback for stm32f1
- unset the **right** callback for stm32f3

### CODE REVIEW

**Comment by polybassa** [comment]
Thanks for this PR. 
One little remark, could you please verify, that you are using uncrustify  version 0.67_f

**Comment by HeMe2** [comment]
I'm Sorry!
Now I upgraded to version 0.67, but I cannot find a tag to 0.67_f. What's the difference between 0.67 and 0.67_f?

**Comment by HeMe2** [comment]
Okay, now I found an archive which compiles to version 0.67_f, but I'm still wondering what's the difference.

**Comment by polybassa** [comment]
I don't know if there is a difference, but 0.67_f was the latest version I found. I just want to make sure, that we don't have incompatible results after a uncrustify execute

**Comment by HeMe2** [comment]
According to https://github.com/uncrustify/uncrustify/releases 0.68.1 is the latest. But I don't mind, as long as I can manage to install the right version ;-)

**Comment by polybassa** [comment]
ok.. at the time I did the update, 67_f was the latest version :-)

**Pull request merged**
