### PR TITLE
Hardware abstraction layer for stm32 f4xx controllers

### PR DESCRIPTION
**Pull request by HeMe2**

### CODE REVIEW

**Comment by polybassa** [comment]
Thanks for this PR. 
1. In recent projects, I added a project specific app folder. Your folder discovery_board_f407vg could go there. `project_bluepill_horrorscope` has such a folder, for example. You only need to add this folder to the your `Makefile.prj` `VPATH+=${PRJ_PATH}/apps` and `IPATH+=${PRJ_PATH}/apps`. 
2. Are all of the directories in `libraries/CMSIS/Device/ST/STM32F4xx/Source/Templates/*` required? I assume some directories here could be removed.
3. Could you please add your project to the continuous integration. `.travis.yml`. I would like to enforce a build of this project in order to check that it's dependencies are not broken.

**Comment by HeMe2** [comment]
Okay, I'll take a look at those points. 
Hopefully I can integrate these suggestions until next week.

**Comment by HeMe2** [comment]
Hi polybassa, 

finally I included all mentioned changes. The travis CI fails right now, because it is set to pull from the master branch of your repository, which doesn't include the necessary resources yet. 

It should be passing right after the automerge to master branch.

**Comment by HeMe2** [comment]
Well... now it is working

**Comment by polybassa** [comment]
Hi Henning,
I will squash and merge your PR
Sorry for the delay

**Comment by HeMe2** [comment]
Hi Nils, 
nevermind. Maybe you should update the repo's description to indicate that STM_HAL now supports F4 controllers, too.

**Pull request merged**
